name: CI

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'info'
  push:
    branches: [ main, m4 ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
      
    - name: Install apt-get packages
      run: |
        echo RESET grub-efi/install_devices | sudo debconf-communicate grub-pc
        sudo ACCEPT_EULA=Y apt-get update
        sudo ACCEPT_EULA=Y apt-get upgrade
        sudo apt-get install wget git curl software-properties-common build-essential
    
    - name: Install Rust target for wasm
      run: |
        rustup target add wasm32-wasi
        
    - name: Install WasmEdge
      run: |
        VERSION=0.11.2
        curl -sSf https://raw.githubusercontent.com/WasmEdge/WasmEdge/master/utils/install.sh | sudo bash -s -- -e all --version=$VERSION -p /usr/local
    
    - name: microservice
      run: |
        cargo build --target wasm32-wasi --release
        wasmedgec target/wasm32-wasi/release/sales_tax_rate_lookup.wasm sales_tax_rate_lookup.wasm
        nohup wasmedge sales_tax_rate_lookup.wasm &
        echo $! > wasmedge.pid
        sleep 15
        resp=$(curl http://localhost:8001/find_rate -X POST -d "78701")
        echo "$resp"
        if [[ $resp == "0.0825" ]]; then
          echo -e "Execution Success!"
        else
          echo -e "Execution Fail!"
          exit 1
        fi
        resp=$(curl http://localhost:8001/find_rate -X POST -d "54921")
        echo "$resp"
        if [[ $resp == "0.055" ]]; then
          echo -e "Execution Success!"
        else
          echo -e "Execution Fail!"
          exit 1
        fi
        resp=$(curl -v http://localhost:8001/find_rate -X POST -d "12345" 2>&1)
        echo "$resp"
        if [[ $resp == *"404 Not Found"* ]]; then
          echo -e "Execution Success!"
        else
          echo -e "Execution Fail!"
          exit 1
        fi
        kill -9 `cat wasmedge.pid`
        rm wasmedge.pid
